title: Accro-branché
default_lang: fr
author:
  name: Accro-branché
  email: michael.lemay@lilo.org
taxonomies:
  - category
  - tag
metadata:
  title: 'Accrobranché | Association d''accrobranche'
  description: 'Accrobranché est le site de référence d''accrobranche dans le Nord'
summary:
  enabled: true
  format: short
  size: 150
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
